### ISSUE TITLE
Favorite ponies not loaded when simulator is restarted

### ISSUE THREAD

**Issue by normbarnard** [rickbdotcom/ponyfaces_maestro#1]
When I fire up the app, select some pony faces and mark them as favorites, and then kill the simulator and restart it. My list of favorite pony faces is empty. I would have expected to see my marked favorites displayed in the favorites tab.

I should mention, I work at Maestro.  If you could fix that one issue that'd be great. App looks good otherwise.

**Comment by rickbdotcom** [comment]
Eh, I must have missed a save. I'll take a look. :)

**Comment by rickbdotcom** [comment]
Oh right duh, saveWithBlock takes place on a different thread so I need to get the object in the localContext. Doh!

**Comment by rickbdotcom** [comment]
OK that should be fixed now.

**Comment by normbarnard** [comment]
Confirmed. Thanks!
